/*
 * api/v1/activity_service.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing Apiv1WorkspaceStorageSetting
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class Apiv1WorkspaceStorageSettingTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Apiv1WorkspaceStorageSetting
        //private Apiv1WorkspaceStorageSetting instance;

        public Apiv1WorkspaceStorageSettingTests()
        {
            // TODO uncomment below to create an instance of Apiv1WorkspaceStorageSetting
            //instance = new Apiv1WorkspaceStorageSetting();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Apiv1WorkspaceStorageSetting
        /// </summary>
        [Fact]
        public void Apiv1WorkspaceStorageSettingInstanceTest()
        {
            // TODO uncomment below to test "IsType" Apiv1WorkspaceStorageSetting
            //Assert.IsType<Apiv1WorkspaceStorageSetting>(instance);
        }

        /// <summary>
        /// Test the property 'StorageType'
        /// </summary>
        [Fact]
        public void StorageTypeTest()
        {
            // TODO unit test for the property 'StorageType'
        }

        /// <summary>
        /// Test the property 'FilepathTemplate'
        /// </summary>
        [Fact]
        public void FilepathTemplateTest()
        {
            // TODO unit test for the property 'FilepathTemplate'
        }

        /// <summary>
        /// Test the property 'UploadSizeLimitMb'
        /// </summary>
        [Fact]
        public void UploadSizeLimitMbTest()
        {
            // TODO unit test for the property 'UploadSizeLimitMb'
        }

        /// <summary>
        /// Test the property 'S3Config'
        /// </summary>
        [Fact]
        public void S3ConfigTest()
        {
            // TODO unit test for the property 'S3Config'
        }
    }
}
