/*
 * api/v1/activity_service.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing Apiv1IdentityProviderConfig
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class Apiv1IdentityProviderConfigTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Apiv1IdentityProviderConfig
        //private Apiv1IdentityProviderConfig instance;

        public Apiv1IdentityProviderConfigTests()
        {
            // TODO uncomment below to create an instance of Apiv1IdentityProviderConfig
            //instance = new Apiv1IdentityProviderConfig();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Apiv1IdentityProviderConfig
        /// </summary>
        [Fact]
        public void Apiv1IdentityProviderConfigInstanceTest()
        {
            // TODO uncomment below to test "IsType" Apiv1IdentityProviderConfig
            //Assert.IsType<Apiv1IdentityProviderConfig>(instance);
        }

        /// <summary>
        /// Test the property 'Oauth2Config'
        /// </summary>
        [Fact]
        public void Oauth2ConfigTest()
        {
            // TODO unit test for the property 'Oauth2Config'
        }
    }
}
