/*
 * api/v1/activity_service.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing Apiv1ActivityMemoCommentPayload
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class Apiv1ActivityMemoCommentPayloadTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Apiv1ActivityMemoCommentPayload
        //private Apiv1ActivityMemoCommentPayload instance;

        public Apiv1ActivityMemoCommentPayloadTests()
        {
            // TODO uncomment below to create an instance of Apiv1ActivityMemoCommentPayload
            //instance = new Apiv1ActivityMemoCommentPayload();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Apiv1ActivityMemoCommentPayload
        /// </summary>
        [Fact]
        public void Apiv1ActivityMemoCommentPayloadInstanceTest()
        {
            // TODO uncomment below to test "IsType" Apiv1ActivityMemoCommentPayload
            //Assert.IsType<Apiv1ActivityMemoCommentPayload>(instance);
        }

        /// <summary>
        /// Test the property 'MemoId'
        /// </summary>
        [Fact]
        public void MemoIdTest()
        {
            // TODO unit test for the property 'MemoId'
        }

        /// <summary>
        /// Test the property 'RelatedMemoId'
        /// </summary>
        [Fact]
        public void RelatedMemoIdTest()
        {
            // TODO unit test for the property 'RelatedMemoId'
        }
    }
}
