/*
 * api/v1/activity_service.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing Apiv1WorkspaceStorageSettingStorageType
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class Apiv1WorkspaceStorageSettingStorageTypeTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Apiv1WorkspaceStorageSettingStorageType
        //private Apiv1WorkspaceStorageSettingStorageType instance;

        public Apiv1WorkspaceStorageSettingStorageTypeTests()
        {
            // TODO uncomment below to create an instance of Apiv1WorkspaceStorageSettingStorageType
            //instance = new Apiv1WorkspaceStorageSettingStorageType();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Apiv1WorkspaceStorageSettingStorageType
        /// </summary>
        [Fact]
        public void Apiv1WorkspaceStorageSettingStorageTypeInstanceTest()
        {
            // TODO uncomment below to test "IsType" Apiv1WorkspaceStorageSettingStorageType
            //Assert.IsType<Apiv1WorkspaceStorageSettingStorageType>(instance);
        }
    }
}
