/*
 * api/v1/activity_service.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing Apiv1OAuth2Config
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class Apiv1OAuth2ConfigTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Apiv1OAuth2Config
        //private Apiv1OAuth2Config instance;

        public Apiv1OAuth2ConfigTests()
        {
            // TODO uncomment below to create an instance of Apiv1OAuth2Config
            //instance = new Apiv1OAuth2Config();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Apiv1OAuth2Config
        /// </summary>
        [Fact]
        public void Apiv1OAuth2ConfigInstanceTest()
        {
            // TODO uncomment below to test "IsType" Apiv1OAuth2Config
            //Assert.IsType<Apiv1OAuth2Config>(instance);
        }

        /// <summary>
        /// Test the property 'ClientId'
        /// </summary>
        [Fact]
        public void ClientIdTest()
        {
            // TODO unit test for the property 'ClientId'
        }

        /// <summary>
        /// Test the property 'ClientSecret'
        /// </summary>
        [Fact]
        public void ClientSecretTest()
        {
            // TODO unit test for the property 'ClientSecret'
        }

        /// <summary>
        /// Test the property 'AuthUrl'
        /// </summary>
        [Fact]
        public void AuthUrlTest()
        {
            // TODO unit test for the property 'AuthUrl'
        }

        /// <summary>
        /// Test the property 'TokenUrl'
        /// </summary>
        [Fact]
        public void TokenUrlTest()
        {
            // TODO unit test for the property 'TokenUrl'
        }

        /// <summary>
        /// Test the property 'UserInfoUrl'
        /// </summary>
        [Fact]
        public void UserInfoUrlTest()
        {
            // TODO unit test for the property 'UserInfoUrl'
        }

        /// <summary>
        /// Test the property 'Scopes'
        /// </summary>
        [Fact]
        public void ScopesTest()
        {
            // TODO unit test for the property 'Scopes'
        }

        /// <summary>
        /// Test the property 'FieldMapping'
        /// </summary>
        [Fact]
        public void FieldMappingTest()
        {
            // TODO unit test for the property 'FieldMapping'
        }
    }
}
