/*
 * api/v1/activity_service.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing Apiv1ActivityPayload
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class Apiv1ActivityPayloadTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Apiv1ActivityPayload
        //private Apiv1ActivityPayload instance;

        public Apiv1ActivityPayloadTests()
        {
            // TODO uncomment below to create an instance of Apiv1ActivityPayload
            //instance = new Apiv1ActivityPayload();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Apiv1ActivityPayload
        /// </summary>
        [Fact]
        public void Apiv1ActivityPayloadInstanceTest()
        {
            // TODO uncomment below to test "IsType" Apiv1ActivityPayload
            //Assert.IsType<Apiv1ActivityPayload>(instance);
        }

        /// <summary>
        /// Test the property 'MemoComment'
        /// </summary>
        [Fact]
        public void MemoCommentTest()
        {
            // TODO unit test for the property 'MemoComment'
        }

        /// <summary>
        /// Test the property 'VersionUpdate'
        /// </summary>
        [Fact]
        public void VersionUpdateTest()
        {
            // TODO unit test for the property 'VersionUpdate'
        }
    }
}
