/*
 * api/v1/activity_service.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing Apiv1UserSetting
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class Apiv1UserSettingTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Apiv1UserSetting
        //private Apiv1UserSetting instance;

        public Apiv1UserSettingTests()
        {
            // TODO uncomment below to create an instance of Apiv1UserSetting
            //instance = new Apiv1UserSetting();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Apiv1UserSetting
        /// </summary>
        [Fact]
        public void Apiv1UserSettingInstanceTest()
        {
            // TODO uncomment below to test "IsType" Apiv1UserSetting
            //Assert.IsType<Apiv1UserSetting>(instance);
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Locale'
        /// </summary>
        [Fact]
        public void LocaleTest()
        {
            // TODO unit test for the property 'Locale'
        }

        /// <summary>
        /// Test the property 'Appearance'
        /// </summary>
        [Fact]
        public void AppearanceTest()
        {
            // TODO unit test for the property 'Appearance'
        }

        /// <summary>
        /// Test the property 'MemoVisibility'
        /// </summary>
        [Fact]
        public void MemoVisibilityTest()
        {
            // TODO unit test for the property 'MemoVisibility'
        }
    }
}
