/*
 * api/v1/activity_service.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing Apiv1WorkspaceCustomProfile
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class Apiv1WorkspaceCustomProfileTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Apiv1WorkspaceCustomProfile
        //private Apiv1WorkspaceCustomProfile instance;

        public Apiv1WorkspaceCustomProfileTests()
        {
            // TODO uncomment below to create an instance of Apiv1WorkspaceCustomProfile
            //instance = new Apiv1WorkspaceCustomProfile();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Apiv1WorkspaceCustomProfile
        /// </summary>
        [Fact]
        public void Apiv1WorkspaceCustomProfileInstanceTest()
        {
            // TODO uncomment below to test "IsType" Apiv1WorkspaceCustomProfile
            //Assert.IsType<Apiv1WorkspaceCustomProfile>(instance);
        }

        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Fact]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }

        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }

        /// <summary>
        /// Test the property 'LogoUrl'
        /// </summary>
        [Fact]
        public void LogoUrlTest()
        {
            // TODO unit test for the property 'LogoUrl'
        }

        /// <summary>
        /// Test the property 'Locale'
        /// </summary>
        [Fact]
        public void LocaleTest()
        {
            // TODO unit test for the property 'Locale'
        }

        /// <summary>
        /// Test the property 'Appearance'
        /// </summary>
        [Fact]
        public void AppearanceTest()
        {
            // TODO unit test for the property 'Appearance'
        }
    }
}
