/*
 * api/v1/activity_service.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing MemoServiceSetMemoResourcesBody
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class MemoServiceSetMemoResourcesBodyTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for MemoServiceSetMemoResourcesBody
        //private MemoServiceSetMemoResourcesBody instance;

        public MemoServiceSetMemoResourcesBodyTests()
        {
            // TODO uncomment below to create an instance of MemoServiceSetMemoResourcesBody
            //instance = new MemoServiceSetMemoResourcesBody();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of MemoServiceSetMemoResourcesBody
        /// </summary>
        [Fact]
        public void MemoServiceSetMemoResourcesBodyInstanceTest()
        {
            // TODO uncomment below to test "IsType" MemoServiceSetMemoResourcesBody
            //Assert.IsType<MemoServiceSetMemoResourcesBody>(instance);
        }

        /// <summary>
        /// Test the property 'Resources'
        /// </summary>
        [Fact]
        public void ResourcesTest()
        {
            // TODO unit test for the property 'Resources'
        }
    }
}
