/*
 * api/v1/activity_service.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing MemoServiceSetMemoRelationsBody
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class MemoServiceSetMemoRelationsBodyTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for MemoServiceSetMemoRelationsBody
        //private MemoServiceSetMemoRelationsBody instance;

        public MemoServiceSetMemoRelationsBodyTests()
        {
            // TODO uncomment below to create an instance of MemoServiceSetMemoRelationsBody
            //instance = new MemoServiceSetMemoRelationsBody();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of MemoServiceSetMemoRelationsBody
        /// </summary>
        [Fact]
        public void MemoServiceSetMemoRelationsBodyInstanceTest()
        {
            // TODO uncomment below to test "IsType" MemoServiceSetMemoRelationsBody
            //Assert.IsType<MemoServiceSetMemoRelationsBody>(instance);
        }

        /// <summary>
        /// Test the property 'Relations'
        /// </summary>
        [Fact]
        public void RelationsTest()
        {
            // TODO unit test for the property 'Relations'
        }
    }
}
