/*
 * api/v1/activity_service.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing MemoServiceRenameMemoTagBody
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class MemoServiceRenameMemoTagBodyTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for MemoServiceRenameMemoTagBody
        //private MemoServiceRenameMemoTagBody instance;

        public MemoServiceRenameMemoTagBodyTests()
        {
            // TODO uncomment below to create an instance of MemoServiceRenameMemoTagBody
            //instance = new MemoServiceRenameMemoTagBody();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of MemoServiceRenameMemoTagBody
        /// </summary>
        [Fact]
        public void MemoServiceRenameMemoTagBodyInstanceTest()
        {
            // TODO uncomment below to test "IsType" MemoServiceRenameMemoTagBody
            //Assert.IsType<MemoServiceRenameMemoTagBody>(instance);
        }

        /// <summary>
        /// Test the property 'OldTag'
        /// </summary>
        [Fact]
        public void OldTagTest()
        {
            // TODO unit test for the property 'OldTag'
        }

        /// <summary>
        /// Test the property 'NewTag'
        /// </summary>
        [Fact]
        public void NewTagTest()
        {
            // TODO unit test for the property 'NewTag'
        }
    }
}
