/*
 * api/v1/activity_service.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing MemoServiceUpsertMemoReactionBody
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class MemoServiceUpsertMemoReactionBodyTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for MemoServiceUpsertMemoReactionBody
        //private MemoServiceUpsertMemoReactionBody instance;

        public MemoServiceUpsertMemoReactionBodyTests()
        {
            // TODO uncomment below to create an instance of MemoServiceUpsertMemoReactionBody
            //instance = new MemoServiceUpsertMemoReactionBody();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of MemoServiceUpsertMemoReactionBody
        /// </summary>
        [Fact]
        public void MemoServiceUpsertMemoReactionBodyInstanceTest()
        {
            // TODO uncomment below to test "IsType" MemoServiceUpsertMemoReactionBody
            //Assert.IsType<MemoServiceUpsertMemoReactionBody>(instance);
        }

        /// <summary>
        /// Test the property 'Reaction'
        /// </summary>
        [Fact]
        public void ReactionTest()
        {
            // TODO unit test for the property 'Reaction'
        }
    }
}
