/*
 * api/v1/activity_service.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing SettingIsTheSettingToUpdate
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SettingIsTheSettingToUpdateTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SettingIsTheSettingToUpdate
        //private SettingIsTheSettingToUpdate instance;

        public SettingIsTheSettingToUpdateTests()
        {
            // TODO uncomment below to create an instance of SettingIsTheSettingToUpdate
            //instance = new SettingIsTheSettingToUpdate();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SettingIsTheSettingToUpdate
        /// </summary>
        [Fact]
        public void SettingIsTheSettingToUpdateInstanceTest()
        {
            // TODO uncomment below to test "IsType" SettingIsTheSettingToUpdate
            //Assert.IsType<SettingIsTheSettingToUpdate>(instance);
        }

        /// <summary>
        /// Test the property 'GeneralSetting'
        /// </summary>
        [Fact]
        public void GeneralSettingTest()
        {
            // TODO unit test for the property 'GeneralSetting'
        }

        /// <summary>
        /// Test the property 'StorageSetting'
        /// </summary>
        [Fact]
        public void StorageSettingTest()
        {
            // TODO unit test for the property 'StorageSetting'
        }

        /// <summary>
        /// Test the property 'MemoRelatedSetting'
        /// </summary>
        [Fact]
        public void MemoRelatedSettingTest()
        {
            // TODO unit test for the property 'MemoRelatedSetting'
        }
    }
}
