/*
 * api/v1/activity_service.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing TheIdentityProviderToUpdate
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TheIdentityProviderToUpdateTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TheIdentityProviderToUpdate
        //private TheIdentityProviderToUpdate instance;

        public TheIdentityProviderToUpdateTests()
        {
            // TODO uncomment below to create an instance of TheIdentityProviderToUpdate
            //instance = new TheIdentityProviderToUpdate();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TheIdentityProviderToUpdate
        /// </summary>
        [Fact]
        public void TheIdentityProviderToUpdateInstanceTest()
        {
            // TODO uncomment below to test "IsType" TheIdentityProviderToUpdate
            //Assert.IsType<TheIdentityProviderToUpdate>(instance);
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Fact]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }

        /// <summary>
        /// Test the property 'IdentifierFilter'
        /// </summary>
        [Fact]
        public void IdentifierFilterTest()
        {
            // TODO unit test for the property 'IdentifierFilter'
        }

        /// <summary>
        /// Test the property 'Config'
        /// </summary>
        [Fact]
        public void ConfigTest()
        {
            // TODO unit test for the property 'Config'
        }
    }
}
