/*
 * api/v1/activity_service.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing UserServiceCreateUserAccessTokenBody
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UserServiceCreateUserAccessTokenBodyTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UserServiceCreateUserAccessTokenBody
        //private UserServiceCreateUserAccessTokenBody instance;

        public UserServiceCreateUserAccessTokenBodyTests()
        {
            // TODO uncomment below to create an instance of UserServiceCreateUserAccessTokenBody
            //instance = new UserServiceCreateUserAccessTokenBody();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UserServiceCreateUserAccessTokenBody
        /// </summary>
        [Fact]
        public void UserServiceCreateUserAccessTokenBodyInstanceTest()
        {
            // TODO uncomment below to test "IsType" UserServiceCreateUserAccessTokenBody
            //Assert.IsType<UserServiceCreateUserAccessTokenBody>(instance);
        }

        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }

        /// <summary>
        /// Test the property 'ExpiresAt'
        /// </summary>
        [Fact]
        public void ExpiresAtTest()
        {
            // TODO unit test for the property 'ExpiresAt'
        }
    }
}
