/*
 * api/v1/activity_service.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing V1Activity
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class V1ActivityTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for V1Activity
        //private V1Activity instance;

        public V1ActivityTests()
        {
            // TODO uncomment below to create an instance of V1Activity
            //instance = new V1Activity();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of V1Activity
        /// </summary>
        [Fact]
        public void V1ActivityInstanceTest()
        {
            // TODO uncomment below to test "IsType" V1Activity
            //Assert.IsType<V1Activity>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'CreatorId'
        /// </summary>
        [Fact]
        public void CreatorIdTest()
        {
            // TODO unit test for the property 'CreatorId'
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

        /// <summary>
        /// Test the property 'Level'
        /// </summary>
        [Fact]
        public void LevelTest()
        {
            // TODO unit test for the property 'Level'
        }

        /// <summary>
        /// Test the property 'CreateTime'
        /// </summary>
        [Fact]
        public void CreateTimeTest()
        {
            // TODO unit test for the property 'CreateTime'
        }

        /// <summary>
        /// Test the property 'Payload'
        /// </summary>
        [Fact]
        public void PayloadTest()
        {
            // TODO unit test for the property 'Payload'
        }
    }
}
