/*
 * api/v1/activity_service.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing V1CreateWebhookRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class V1CreateWebhookRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for V1CreateWebhookRequest
        //private V1CreateWebhookRequest instance;

        public V1CreateWebhookRequestTests()
        {
            // TODO uncomment below to create an instance of V1CreateWebhookRequest
            //instance = new V1CreateWebhookRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of V1CreateWebhookRequest
        /// </summary>
        [Fact]
        public void V1CreateWebhookRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" V1CreateWebhookRequest
            //Assert.IsType<V1CreateWebhookRequest>(instance);
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Url'
        /// </summary>
        [Fact]
        public void UrlTest()
        {
            // TODO unit test for the property 'Url'
        }
    }
}
