/*
 * api/v1/activity_service.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing V1ListMemoReactionsResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class V1ListMemoReactionsResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for V1ListMemoReactionsResponse
        //private V1ListMemoReactionsResponse instance;

        public V1ListMemoReactionsResponseTests()
        {
            // TODO uncomment below to create an instance of V1ListMemoReactionsResponse
            //instance = new V1ListMemoReactionsResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of V1ListMemoReactionsResponse
        /// </summary>
        [Fact]
        public void V1ListMemoReactionsResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" V1ListMemoReactionsResponse
            //Assert.IsType<V1ListMemoReactionsResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Reactions'
        /// </summary>
        [Fact]
        public void ReactionsTest()
        {
            // TODO unit test for the property 'Reactions'
        }
    }
}
