/*
 * api/v1/activity_service.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing V1MemoProperty
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class V1MemoPropertyTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for V1MemoProperty
        //private V1MemoProperty instance;

        public V1MemoPropertyTests()
        {
            // TODO uncomment below to create an instance of V1MemoProperty
            //instance = new V1MemoProperty();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of V1MemoProperty
        /// </summary>
        [Fact]
        public void V1MemoPropertyInstanceTest()
        {
            // TODO uncomment below to test "IsType" V1MemoProperty
            //Assert.IsType<V1MemoProperty>(instance);
        }

        /// <summary>
        /// Test the property 'Tags'
        /// </summary>
        [Fact]
        public void TagsTest()
        {
            // TODO unit test for the property 'Tags'
        }

        /// <summary>
        /// Test the property 'HasLink'
        /// </summary>
        [Fact]
        public void HasLinkTest()
        {
            // TODO unit test for the property 'HasLink'
        }

        /// <summary>
        /// Test the property 'HasTaskList'
        /// </summary>
        [Fact]
        public void HasTaskListTest()
        {
            // TODO unit test for the property 'HasTaskList'
        }

        /// <summary>
        /// Test the property 'HasCode'
        /// </summary>
        [Fact]
        public void HasCodeTest()
        {
            // TODO unit test for the property 'HasCode'
        }
    }
}
