/*
 * api/v1/activity_service.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing V1ReactionType
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class V1ReactionTypeTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for V1ReactionType
        //private V1ReactionType instance;

        public V1ReactionTypeTests()
        {
            // TODO uncomment below to create an instance of V1ReactionType
            //instance = new V1ReactionType();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of V1ReactionType
        /// </summary>
        [Fact]
        public void V1ReactionTypeInstanceTest()
        {
            // TODO uncomment below to test "IsType" V1ReactionType
            //Assert.IsType<V1ReactionType>(instance);
        }
    }
}
