/*
 * api/v1/activity_service.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing V1RestoreMarkdownRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class V1RestoreMarkdownRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for V1RestoreMarkdownRequest
        //private V1RestoreMarkdownRequest instance;

        public V1RestoreMarkdownRequestTests()
        {
            // TODO uncomment below to create an instance of V1RestoreMarkdownRequest
            //instance = new V1RestoreMarkdownRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of V1RestoreMarkdownRequest
        /// </summary>
        [Fact]
        public void V1RestoreMarkdownRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" V1RestoreMarkdownRequest
            //Assert.IsType<V1RestoreMarkdownRequest>(instance);
        }

        /// <summary>
        /// Test the property 'Nodes'
        /// </summary>
        [Fact]
        public void NodesTest()
        {
            // TODO unit test for the property 'Nodes'
        }
    }
}
