/*
 * api/v1/activity_service.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing V1RestoreMarkdownResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class V1RestoreMarkdownResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for V1RestoreMarkdownResponse
        //private V1RestoreMarkdownResponse instance;

        public V1RestoreMarkdownResponseTests()
        {
            // TODO uncomment below to create an instance of V1RestoreMarkdownResponse
            //instance = new V1RestoreMarkdownResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of V1RestoreMarkdownResponse
        /// </summary>
        [Fact]
        public void V1RestoreMarkdownResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" V1RestoreMarkdownResponse
            //Assert.IsType<V1RestoreMarkdownResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Markdown'
        /// </summary>
        [Fact]
        public void MarkdownTest()
        {
            // TODO unit test for the property 'Markdown'
        }
    }
}
