/*
 * api/v1/activity_service.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing V1RowStatus
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class V1RowStatusTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for V1RowStatus
        //private V1RowStatus instance;

        public V1RowStatusTests()
        {
            // TODO uncomment below to create an instance of V1RowStatus
            //instance = new V1RowStatus();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of V1RowStatus
        /// </summary>
        [Fact]
        public void V1RowStatusInstanceTest()
        {
            // TODO uncomment below to test "IsType" V1RowStatus
            //Assert.IsType<V1RowStatus>(instance);
        }
    }
}
