/*
 * api/v1/activity_service.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing V1UserAccessToken
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class V1UserAccessTokenTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for V1UserAccessToken
        //private V1UserAccessToken instance;

        public V1UserAccessTokenTests()
        {
            // TODO uncomment below to create an instance of V1UserAccessToken
            //instance = new V1UserAccessToken();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of V1UserAccessToken
        /// </summary>
        [Fact]
        public void V1UserAccessTokenInstanceTest()
        {
            // TODO uncomment below to test "IsType" V1UserAccessToken
            //Assert.IsType<V1UserAccessToken>(instance);
        }

        /// <summary>
        /// Test the property 'AccessToken'
        /// </summary>
        [Fact]
        public void AccessTokenTest()
        {
            // TODO unit test for the property 'AccessToken'
        }

        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }

        /// <summary>
        /// Test the property 'IssuedAt'
        /// </summary>
        [Fact]
        public void IssuedAtTest()
        {
            // TODO unit test for the property 'IssuedAt'
        }

        /// <summary>
        /// Test the property 'ExpiresAt'
        /// </summary>
        [Fact]
        public void ExpiresAtTest()
        {
            // TODO unit test for the property 'ExpiresAt'
        }
    }
}
