/*
 * api/v1/activity_service.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// Defines UserRole
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum UserRole
    {
        /// <summary>
        /// Enum ROLEUNSPECIFIED for value: ROLE_UNSPECIFIED
        /// </summary>
        [EnumMember(Value = "ROLE_UNSPECIFIED")]
        ROLEUNSPECIFIED = 1,

        /// <summary>
        /// Enum HOST for value: HOST
        /// </summary>
        [EnumMember(Value = "HOST")]
        HOST = 2,

        /// <summary>
        /// Enum ADMIN for value: ADMIN
        /// </summary>
        [EnumMember(Value = "ADMIN")]
        ADMIN = 3,

        /// <summary>
        /// Enum USER for value: USER
        /// </summary>
        [EnumMember(Value = "USER")]
        USER = 4
    }

}
