/*
 * api/v1/activity_service.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// Defines v1NodeType
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum V1NodeType
    {
        /// <summary>
        /// Enum NODEUNSPECIFIED for value: NODE_UNSPECIFIED
        /// </summary>
        [EnumMember(Value = "NODE_UNSPECIFIED")]
        NODEUNSPECIFIED = 1,

        /// <summary>
        /// Enum LINEBREAK for value: LINE_BREAK
        /// </summary>
        [EnumMember(Value = "LINE_BREAK")]
        LINEBREAK = 2,

        /// <summary>
        /// Enum PARAGRAPH for value: PARAGRAPH
        /// </summary>
        [EnumMember(Value = "PARAGRAPH")]
        PARAGRAPH = 3,

        /// <summary>
        /// Enum CODEBLOCK for value: CODE_BLOCK
        /// </summary>
        [EnumMember(Value = "CODE_BLOCK")]
        CODEBLOCK = 4,

        /// <summary>
        /// Enum HEADING for value: HEADING
        /// </summary>
        [EnumMember(Value = "HEADING")]
        HEADING = 5,

        /// <summary>
        /// Enum HORIZONTALRULE for value: HORIZONTAL_RULE
        /// </summary>
        [EnumMember(Value = "HORIZONTAL_RULE")]
        HORIZONTALRULE = 6,

        /// <summary>
        /// Enum BLOCKQUOTE for value: BLOCKQUOTE
        /// </summary>
        [EnumMember(Value = "BLOCKQUOTE")]
        BLOCKQUOTE = 7,

        /// <summary>
        /// Enum ORDEREDLIST for value: ORDERED_LIST
        /// </summary>
        [EnumMember(Value = "ORDERED_LIST")]
        ORDEREDLIST = 8,

        /// <summary>
        /// Enum UNORDEREDLIST for value: UNORDERED_LIST
        /// </summary>
        [EnumMember(Value = "UNORDERED_LIST")]
        UNORDEREDLIST = 9,

        /// <summary>
        /// Enum TASKLIST for value: TASK_LIST
        /// </summary>
        [EnumMember(Value = "TASK_LIST")]
        TASKLIST = 10,

        /// <summary>
        /// Enum MATHBLOCK for value: MATH_BLOCK
        /// </summary>
        [EnumMember(Value = "MATH_BLOCK")]
        MATHBLOCK = 11,

        /// <summary>
        /// Enum TABLE for value: TABLE
        /// </summary>
        [EnumMember(Value = "TABLE")]
        TABLE = 12,

        /// <summary>
        /// Enum EMBEDDEDCONTENT for value: EMBEDDED_CONTENT
        /// </summary>
        [EnumMember(Value = "EMBEDDED_CONTENT")]
        EMBEDDEDCONTENT = 13,

        /// <summary>
        /// Enum TEXT for value: TEXT
        /// </summary>
        [EnumMember(Value = "TEXT")]
        TEXT = 14,

        /// <summary>
        /// Enum BOLD for value: BOLD
        /// </summary>
        [EnumMember(Value = "BOLD")]
        BOLD = 15,

        /// <summary>
        /// Enum ITALIC for value: ITALIC
        /// </summary>
        [EnumMember(Value = "ITALIC")]
        ITALIC = 16,

        /// <summary>
        /// Enum BOLDITALIC for value: BOLD_ITALIC
        /// </summary>
        [EnumMember(Value = "BOLD_ITALIC")]
        BOLDITALIC = 17,

        /// <summary>
        /// Enum CODE for value: CODE
        /// </summary>
        [EnumMember(Value = "CODE")]
        CODE = 18,

        /// <summary>
        /// Enum IMAGE for value: IMAGE
        /// </summary>
        [EnumMember(Value = "IMAGE")]
        IMAGE = 19,

        /// <summary>
        /// Enum LINK for value: LINK
        /// </summary>
        [EnumMember(Value = "LINK")]
        LINK = 20,

        /// <summary>
        /// Enum AUTOLINK for value: AUTO_LINK
        /// </summary>
        [EnumMember(Value = "AUTO_LINK")]
        AUTOLINK = 21,

        /// <summary>
        /// Enum TAG for value: TAG
        /// </summary>
        [EnumMember(Value = "TAG")]
        TAG = 22,

        /// <summary>
        /// Enum STRIKETHROUGH for value: STRIKETHROUGH
        /// </summary>
        [EnumMember(Value = "STRIKETHROUGH")]
        STRIKETHROUGH = 23,

        /// <summary>
        /// Enum ESCAPINGCHARACTER for value: ESCAPING_CHARACTER
        /// </summary>
        [EnumMember(Value = "ESCAPING_CHARACTER")]
        ESCAPINGCHARACTER = 24,

        /// <summary>
        /// Enum MATH for value: MATH
        /// </summary>
        [EnumMember(Value = "MATH")]
        MATH = 25,

        /// <summary>
        /// Enum HIGHLIGHT for value: HIGHLIGHT
        /// </summary>
        [EnumMember(Value = "HIGHLIGHT")]
        HIGHLIGHT = 26,

        /// <summary>
        /// Enum SUBSCRIPT for value: SUBSCRIPT
        /// </summary>
        [EnumMember(Value = "SUBSCRIPT")]
        SUBSCRIPT = 27,

        /// <summary>
        /// Enum SUPERSCRIPT for value: SUPERSCRIPT
        /// </summary>
        [EnumMember(Value = "SUPERSCRIPT")]
        SUPERSCRIPT = 28,

        /// <summary>
        /// Enum REFERENCEDCONTENT for value: REFERENCED_CONTENT
        /// </summary>
        [EnumMember(Value = "REFERENCED_CONTENT")]
        REFERENCEDCONTENT = 29,

        /// <summary>
        /// Enum SPOILER for value: SPOILER
        /// </summary>
        [EnumMember(Value = "SPOILER")]
        SPOILER = 30
    }

}
