/*
 * api/v1/activity_service.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// Defines v1ReactionType
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum V1ReactionType
    {
        /// <summary>
        /// Enum TYPEUNSPECIFIED for value: TYPE_UNSPECIFIED
        /// </summary>
        [EnumMember(Value = "TYPE_UNSPECIFIED")]
        TYPEUNSPECIFIED = 1,

        /// <summary>
        /// Enum THUMBSUP for value: THUMBS_UP
        /// </summary>
        [EnumMember(Value = "THUMBS_UP")]
        THUMBSUP = 2,

        /// <summary>
        /// Enum THUMBSDOWN for value: THUMBS_DOWN
        /// </summary>
        [EnumMember(Value = "THUMBS_DOWN")]
        THUMBSDOWN = 3,

        /// <summary>
        /// Enum HEART for value: HEART
        /// </summary>
        [EnumMember(Value = "HEART")]
        HEART = 4,

        /// <summary>
        /// Enum FIRE for value: FIRE
        /// </summary>
        [EnumMember(Value = "FIRE")]
        FIRE = 5,

        /// <summary>
        /// Enum CLAPPINGHANDS for value: CLAPPING_HANDS
        /// </summary>
        [EnumMember(Value = "CLAPPING_HANDS")]
        CLAPPINGHANDS = 6,

        /// <summary>
        /// Enum LAUGH for value: LAUGH
        /// </summary>
        [EnumMember(Value = "LAUGH")]
        LAUGH = 7,

        /// <summary>
        /// Enum OKHAND for value: OK_HAND
        /// </summary>
        [EnumMember(Value = "OK_HAND")]
        OKHAND = 8,

        /// <summary>
        /// Enum ROCKET for value: ROCKET
        /// </summary>
        [EnumMember(Value = "ROCKET")]
        ROCKET = 9,

        /// <summary>
        /// Enum EYES for value: EYES
        /// </summary>
        [EnumMember(Value = "EYES")]
        EYES = 10,

        /// <summary>
        /// Enum THINKINGFACE for value: THINKING_FACE
        /// </summary>
        [EnumMember(Value = "THINKING_FACE")]
        THINKINGFACE = 11,

        /// <summary>
        /// Enum CLOWNFACE for value: CLOWN_FACE
        /// </summary>
        [EnumMember(Value = "CLOWN_FACE")]
        CLOWNFACE = 12,

        /// <summary>
        /// Enum QUESTIONMARK for value: QUESTION_MARK
        /// </summary>
        [EnumMember(Value = "QUESTION_MARK")]
        QUESTIONMARK = 13
    }

}
