/*
 * api/v1/activity_service.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// Defines v1Visibility
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum V1Visibility
    {
        /// <summary>
        /// Enum VISIBILITYUNSPECIFIED for value: VISIBILITY_UNSPECIFIED
        /// </summary>
        [EnumMember(Value = "VISIBILITY_UNSPECIFIED")]
        VISIBILITYUNSPECIFIED = 1,

        /// <summary>
        /// Enum PRIVATE for value: PRIVATE
        /// </summary>
        [EnumMember(Value = "PRIVATE")]
        PRIVATE = 2,

        /// <summary>
        /// Enum PROTECTED for value: PROTECTED
        /// </summary>
        [EnumMember(Value = "PROTECTED")]
        PROTECTED = 3,

        /// <summary>
        /// Enum PUBLIC for value: PUBLIC
        /// </summary>
        [EnumMember(Value = "PUBLIC")]
        PUBLIC = 4
    }

}
