/*
 * api/v1/activity_service.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// V1WorkspaceProfile
    /// </summary>
    [DataContract(Name = "v1WorkspaceProfile")]
    public partial class V1WorkspaceProfile : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="V1WorkspaceProfile" /> class.
        /// </summary>
        /// <param name="owner">owner.</param>
        /// <param name="varVersion">varVersion.</param>
        /// <param name="mode">mode is the instance mode (e.g. \&quot;prod\&quot;, \&quot;dev\&quot; or \&quot;demo\&quot;)..</param>
        public V1WorkspaceProfile(string owner = default(string), string varVersion = default(string), string mode = default(string))
        {
            this.Owner = owner;
            this.VarVersion = varVersion;
            this.Mode = mode;
        }

        /// <summary>
        /// Gets or Sets Owner
        /// </summary>
        [DataMember(Name = "owner", EmitDefaultValue = false)]
        public string Owner { get; set; }

        /// <summary>
        /// Gets or Sets VarVersion
        /// </summary>
        [DataMember(Name = "version", EmitDefaultValue = false)]
        public string VarVersion { get; set; }

        /// <summary>
        /// mode is the instance mode (e.g. \&quot;prod\&quot;, \&quot;dev\&quot; or \&quot;demo\&quot;).
        /// </summary>
        /// <value>mode is the instance mode (e.g. \&quot;prod\&quot;, \&quot;dev\&quot; or \&quot;demo\&quot;).</value>
        [DataMember(Name = "mode", EmitDefaultValue = false)]
        public string Mode { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class V1WorkspaceProfile {\n");
            sb.Append("  Owner: ").Append(Owner).Append("\n");
            sb.Append("  VarVersion: ").Append(VarVersion).Append("\n");
            sb.Append("  Mode: ").Append(Mode).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
