/*
 * api/v1/activity_service.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Org.OpenAPITools.Client;
using Org.OpenAPITools.Api;
// uncomment below to import models
//using Org.OpenAPITools.Model;

namespace Org.OpenAPITools.Test.Api
{
    /// <summary>
    ///  Class for testing MarkdownServiceApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class MarkdownServiceApiTests : IDisposable
    {
        private MarkdownServiceApi instance;

        public MarkdownServiceApiTests()
        {
            instance = new MarkdownServiceApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of MarkdownServiceApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' MarkdownServiceApi
            //Assert.IsType<MarkdownServiceApi>(instance);
        }

        /// <summary>
        /// Test MarkdownServiceGetLinkMetadata
        /// </summary>
        [Fact]
        public void MarkdownServiceGetLinkMetadataTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string? link = null;
            //var response = instance.MarkdownServiceGetLinkMetadata(link);
            //Assert.IsType<V1LinkMetadata>(response);
        }

        /// <summary>
        /// Test MarkdownServiceParseMarkdown
        /// </summary>
        [Fact]
        public void MarkdownServiceParseMarkdownTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //V1ParseMarkdownRequest body = null;
            //var response = instance.MarkdownServiceParseMarkdown(body);
            //Assert.IsType<V1ParseMarkdownResponse>(response);
        }

        /// <summary>
        /// Test MarkdownServiceRestoreMarkdown
        /// </summary>
        [Fact]
        public void MarkdownServiceRestoreMarkdownTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //V1RestoreMarkdownRequest body = null;
            //var response = instance.MarkdownServiceRestoreMarkdown(body);
            //Assert.IsType<V1RestoreMarkdownResponse>(response);
        }
    }
}
