/*
 * api/v1/activity_service.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Org.OpenAPITools.Client;
using Org.OpenAPITools.Api;
// uncomment below to import models
//using Org.OpenAPITools.Model;

namespace Org.OpenAPITools.Test.Api
{
    /// <summary>
    ///  Class for testing WorkspaceSettingServiceApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class WorkspaceSettingServiceApiTests : IDisposable
    {
        private WorkspaceSettingServiceApi instance;

        public WorkspaceSettingServiceApiTests()
        {
            instance = new WorkspaceSettingServiceApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of WorkspaceSettingServiceApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' WorkspaceSettingServiceApi
            //Assert.IsType<WorkspaceSettingServiceApi>(instance);
        }

        /// <summary>
        /// Test WorkspaceSettingServiceGetWorkspaceSetting
        /// </summary>
        [Fact]
        public void WorkspaceSettingServiceGetWorkspaceSettingTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string name = null;
            //var response = instance.WorkspaceSettingServiceGetWorkspaceSetting(name);
            //Assert.IsType<Apiv1WorkspaceSetting>(response);
        }

        /// <summary>
        /// Test WorkspaceSettingServiceSetWorkspaceSetting
        /// </summary>
        [Fact]
        public void WorkspaceSettingServiceSetWorkspaceSettingTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string settingName = null;
            //SettingIsTheSettingToUpdate setting = null;
            //var response = instance.WorkspaceSettingServiceSetWorkspaceSetting(settingName, setting);
            //Assert.IsType<Apiv1WorkspaceSetting>(response);
        }
    }
}
