/*
 * api/v1/activity_service.proto
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: version not set
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using Org.OpenAPITools.Client;
using Org.OpenAPITools.Model;

namespace Org.OpenAPITools.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IWorkspaceSettingServiceApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// GetWorkspaceSetting returns the setting by name.
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="name">The resource name of the workspace setting. Format: settings/{setting}</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>Apiv1WorkspaceSetting</returns>
        Apiv1WorkspaceSetting WorkspaceSettingServiceGetWorkspaceSetting(string name, int operationIndex = 0);

        /// <summary>
        /// GetWorkspaceSetting returns the setting by name.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="name">The resource name of the workspace setting. Format: settings/{setting}</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of Apiv1WorkspaceSetting</returns>
        ApiResponse<Apiv1WorkspaceSetting> WorkspaceSettingServiceGetWorkspaceSettingWithHttpInfo(string name, int operationIndex = 0);
        /// <summary>
        /// SetWorkspaceSetting updates the setting.
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="settingName">name is the name of the setting. Format: settings/{setting}</param>
        /// <param name="setting">setting is the setting to update.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>Apiv1WorkspaceSetting</returns>
        Apiv1WorkspaceSetting WorkspaceSettingServiceSetWorkspaceSetting(string settingName, SettingIsTheSettingToUpdate setting, int operationIndex = 0);

        /// <summary>
        /// SetWorkspaceSetting updates the setting.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="settingName">name is the name of the setting. Format: settings/{setting}</param>
        /// <param name="setting">setting is the setting to update.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of Apiv1WorkspaceSetting</returns>
        ApiResponse<Apiv1WorkspaceSetting> WorkspaceSettingServiceSetWorkspaceSettingWithHttpInfo(string settingName, SettingIsTheSettingToUpdate setting, int operationIndex = 0);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IWorkspaceSettingServiceApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// GetWorkspaceSetting returns the setting by name.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="name">The resource name of the workspace setting. Format: settings/{setting}</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Apiv1WorkspaceSetting</returns>
        System.Threading.Tasks.Task<Apiv1WorkspaceSetting> WorkspaceSettingServiceGetWorkspaceSettingAsync(string name, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// GetWorkspaceSetting returns the setting by name.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="name">The resource name of the workspace setting. Format: settings/{setting}</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Apiv1WorkspaceSetting)</returns>
        System.Threading.Tasks.Task<ApiResponse<Apiv1WorkspaceSetting>> WorkspaceSettingServiceGetWorkspaceSettingWithHttpInfoAsync(string name, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// SetWorkspaceSetting updates the setting.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="settingName">name is the name of the setting. Format: settings/{setting}</param>
        /// <param name="setting">setting is the setting to update.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Apiv1WorkspaceSetting</returns>
        System.Threading.Tasks.Task<Apiv1WorkspaceSetting> WorkspaceSettingServiceSetWorkspaceSettingAsync(string settingName, SettingIsTheSettingToUpdate setting, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// SetWorkspaceSetting updates the setting.
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="settingName">name is the name of the setting. Format: settings/{setting}</param>
        /// <param name="setting">setting is the setting to update.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Apiv1WorkspaceSetting)</returns>
        System.Threading.Tasks.Task<ApiResponse<Apiv1WorkspaceSetting>> WorkspaceSettingServiceSetWorkspaceSettingWithHttpInfoAsync(string settingName, SettingIsTheSettingToUpdate setting, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IWorkspaceSettingServiceApi : IWorkspaceSettingServiceApiSync, IWorkspaceSettingServiceApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class WorkspaceSettingServiceApi : IWorkspaceSettingServiceApi
    {
        private Org.OpenAPITools.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="WorkspaceSettingServiceApi"/> class.
        /// </summary>
        /// <returns></returns>
        public WorkspaceSettingServiceApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="WorkspaceSettingServiceApi"/> class.
        /// </summary>
        /// <returns></returns>
        public WorkspaceSettingServiceApi(string basePath)
        {
            this.Configuration = Org.OpenAPITools.Client.Configuration.MergeConfigurations(
                Org.OpenAPITools.Client.GlobalConfiguration.Instance,
                new Org.OpenAPITools.Client.Configuration { BasePath = basePath }
            );
            this.Client = new Org.OpenAPITools.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Org.OpenAPITools.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = Org.OpenAPITools.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="WorkspaceSettingServiceApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public WorkspaceSettingServiceApi(Org.OpenAPITools.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = Org.OpenAPITools.Client.Configuration.MergeConfigurations(
                Org.OpenAPITools.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new Org.OpenAPITools.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new Org.OpenAPITools.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = Org.OpenAPITools.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="WorkspaceSettingServiceApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public WorkspaceSettingServiceApi(Org.OpenAPITools.Client.ISynchronousClient client, Org.OpenAPITools.Client.IAsynchronousClient asyncClient, Org.OpenAPITools.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = Org.OpenAPITools.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public Org.OpenAPITools.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public Org.OpenAPITools.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Org.OpenAPITools.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Org.OpenAPITools.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// GetWorkspaceSetting returns the setting by name. 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="name">The resource name of the workspace setting. Format: settings/{setting}</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>Apiv1WorkspaceSetting</returns>
        public Apiv1WorkspaceSetting WorkspaceSettingServiceGetWorkspaceSetting(string name, int operationIndex = 0)
        {
            Org.OpenAPITools.Client.ApiResponse<Apiv1WorkspaceSetting> localVarResponse = WorkspaceSettingServiceGetWorkspaceSettingWithHttpInfo(name);
            return localVarResponse.Data;
        }

        /// <summary>
        /// GetWorkspaceSetting returns the setting by name. 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="name">The resource name of the workspace setting. Format: settings/{setting}</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of Apiv1WorkspaceSetting</returns>
        public Org.OpenAPITools.Client.ApiResponse<Apiv1WorkspaceSetting> WorkspaceSettingServiceGetWorkspaceSettingWithHttpInfo(string name, int operationIndex = 0)
        {
            // verify the required parameter 'name' is set
            if (name == null)
            {
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'name' when calling WorkspaceSettingServiceApi->WorkspaceSettingServiceGetWorkspaceSetting");
            }

            Org.OpenAPITools.Client.RequestOptions localVarRequestOptions = new Org.OpenAPITools.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Org.OpenAPITools.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Org.OpenAPITools.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("name", Org.OpenAPITools.Client.ClientUtils.ParameterToString(name)); // path parameter

            localVarRequestOptions.Operation = "WorkspaceSettingServiceApi.WorkspaceSettingServiceGetWorkspaceSetting";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = this.Client.Get<Apiv1WorkspaceSetting>("/api/v1/workspace/{name}", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("WorkspaceSettingServiceGetWorkspaceSetting", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// GetWorkspaceSetting returns the setting by name. 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="name">The resource name of the workspace setting. Format: settings/{setting}</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Apiv1WorkspaceSetting</returns>
        public async System.Threading.Tasks.Task<Apiv1WorkspaceSetting> WorkspaceSettingServiceGetWorkspaceSettingAsync(string name, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Org.OpenAPITools.Client.ApiResponse<Apiv1WorkspaceSetting> localVarResponse = await WorkspaceSettingServiceGetWorkspaceSettingWithHttpInfoAsync(name, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// GetWorkspaceSetting returns the setting by name. 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="name">The resource name of the workspace setting. Format: settings/{setting}</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Apiv1WorkspaceSetting)</returns>
        public async System.Threading.Tasks.Task<Org.OpenAPITools.Client.ApiResponse<Apiv1WorkspaceSetting>> WorkspaceSettingServiceGetWorkspaceSettingWithHttpInfoAsync(string name, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'name' is set
            if (name == null)
            {
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'name' when calling WorkspaceSettingServiceApi->WorkspaceSettingServiceGetWorkspaceSetting");
            }


            Org.OpenAPITools.Client.RequestOptions localVarRequestOptions = new Org.OpenAPITools.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Org.OpenAPITools.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Org.OpenAPITools.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("name", Org.OpenAPITools.Client.ClientUtils.ParameterToString(name)); // path parameter

            localVarRequestOptions.Operation = "WorkspaceSettingServiceApi.WorkspaceSettingServiceGetWorkspaceSetting";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<Apiv1WorkspaceSetting>("/api/v1/workspace/{name}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("WorkspaceSettingServiceGetWorkspaceSetting", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// SetWorkspaceSetting updates the setting. 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="settingName">name is the name of the setting. Format: settings/{setting}</param>
        /// <param name="setting">setting is the setting to update.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>Apiv1WorkspaceSetting</returns>
        public Apiv1WorkspaceSetting WorkspaceSettingServiceSetWorkspaceSetting(string settingName, SettingIsTheSettingToUpdate setting, int operationIndex = 0)
        {
            Org.OpenAPITools.Client.ApiResponse<Apiv1WorkspaceSetting> localVarResponse = WorkspaceSettingServiceSetWorkspaceSettingWithHttpInfo(settingName, setting);
            return localVarResponse.Data;
        }

        /// <summary>
        /// SetWorkspaceSetting updates the setting. 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="settingName">name is the name of the setting. Format: settings/{setting}</param>
        /// <param name="setting">setting is the setting to update.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of Apiv1WorkspaceSetting</returns>
        public Org.OpenAPITools.Client.ApiResponse<Apiv1WorkspaceSetting> WorkspaceSettingServiceSetWorkspaceSettingWithHttpInfo(string settingName, SettingIsTheSettingToUpdate setting, int operationIndex = 0)
        {
            // verify the required parameter 'settingName' is set
            if (settingName == null)
            {
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'settingName' when calling WorkspaceSettingServiceApi->WorkspaceSettingServiceSetWorkspaceSetting");
            }

            // verify the required parameter 'setting' is set
            if (setting == null)
            {
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'setting' when calling WorkspaceSettingServiceApi->WorkspaceSettingServiceSetWorkspaceSetting");
            }

            Org.OpenAPITools.Client.RequestOptions localVarRequestOptions = new Org.OpenAPITools.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Org.OpenAPITools.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Org.OpenAPITools.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("setting.name", Org.OpenAPITools.Client.ClientUtils.ParameterToString(settingName)); // path parameter
            localVarRequestOptions.Data = setting;

            localVarRequestOptions.Operation = "WorkspaceSettingServiceApi.WorkspaceSettingServiceSetWorkspaceSetting";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = this.Client.Patch<Apiv1WorkspaceSetting>("/api/v1/workspace/{setting.name}", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("WorkspaceSettingServiceSetWorkspaceSetting", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// SetWorkspaceSetting updates the setting. 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="settingName">name is the name of the setting. Format: settings/{setting}</param>
        /// <param name="setting">setting is the setting to update.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of Apiv1WorkspaceSetting</returns>
        public async System.Threading.Tasks.Task<Apiv1WorkspaceSetting> WorkspaceSettingServiceSetWorkspaceSettingAsync(string settingName, SettingIsTheSettingToUpdate setting, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Org.OpenAPITools.Client.ApiResponse<Apiv1WorkspaceSetting> localVarResponse = await WorkspaceSettingServiceSetWorkspaceSettingWithHttpInfoAsync(settingName, setting, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// SetWorkspaceSetting updates the setting. 
        /// </summary>
        /// <exception cref="Org.OpenAPITools.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="settingName">name is the name of the setting. Format: settings/{setting}</param>
        /// <param name="setting">setting is the setting to update.</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (Apiv1WorkspaceSetting)</returns>
        public async System.Threading.Tasks.Task<Org.OpenAPITools.Client.ApiResponse<Apiv1WorkspaceSetting>> WorkspaceSettingServiceSetWorkspaceSettingWithHttpInfoAsync(string settingName, SettingIsTheSettingToUpdate setting, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'settingName' is set
            if (settingName == null)
            {
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'settingName' when calling WorkspaceSettingServiceApi->WorkspaceSettingServiceSetWorkspaceSetting");
            }

            // verify the required parameter 'setting' is set
            if (setting == null)
            {
                throw new Org.OpenAPITools.Client.ApiException(400, "Missing required parameter 'setting' when calling WorkspaceSettingServiceApi->WorkspaceSettingServiceSetWorkspaceSetting");
            }


            Org.OpenAPITools.Client.RequestOptions localVarRequestOptions = new Org.OpenAPITools.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Org.OpenAPITools.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = Org.OpenAPITools.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("setting.name", Org.OpenAPITools.Client.ClientUtils.ParameterToString(settingName)); // path parameter
            localVarRequestOptions.Data = setting;

            localVarRequestOptions.Operation = "WorkspaceSettingServiceApi.WorkspaceSettingServiceSetWorkspaceSetting";
            localVarRequestOptions.OperationIndex = operationIndex;


            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PatchAsync<Apiv1WorkspaceSetting>("/api/v1/workspace/{setting.name}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("WorkspaceSettingServiceSetWorkspaceSetting", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

    }
}
